### PR TITLE
fix: links without HTTP/HTTPS show correctly

### LINKED ISSUE #3490: Support link in publication that don't have http or https
https://lenster.xyz/posts/0x01d7ea-0x02

<sub>[ENG-18](https://linear.app/heyxyz/issue/ENG-18/support-link-in-publication-that-dont-have-http-or-https)</sub>

### PR DESCRIPTION
**Pull request by bhavya2611**
## What does this PR do?
Links without HTTP/HTTPS show correctly

## Related issues

Fixes #3490 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Emoji

🚀

### CODE REVIEW

File: packages/data/regex.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 const RESTRICTED_SYMBOLS = '☑️✓✔✅';
 
 export const Regex = {
-  url: /(http|https):\/\/([\w+.?])+([\w!#$%&'()*+,./:;=?@\\^~\-]*)?/g,
+  url: /(?:(ftp|http|https):\/\/)?(?:[\w-]+\.)+[a-z]{2,6}\b([\w#%&()+./:=?@~-]*)?/gi,
```
Comment (bigint) [inline packages/data/regex.ts:4]: We don't want ftp urls!

**Review by bigint — CHANGES_REQUESTED** [review]

**Review by bigint — APPROVED** [review]
**LGTM** :shipit: 

LGTM
