### PR TITLE
chore: message overflow issue fixed

### LINKED ISSUE #1067: Scroll overflow is happening in the preview list

### PR DESCRIPTION
**Pull request by bhavya2611**
## What does this PR do?

Fixes #1067

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Send a long, really long message

## Screenshot

image

### CODE REVIEW

File: src/components/Messages/MessagesList.tsx [hunk 1]
```diff
@@ -138,7 +138,12 @@ const MessagesList: FC<MessageListProps> = ({
           <InfiniteScroll
             dataLength={messages.length}
             next={fetchNextMessages}
-            style={{ display: 'flex', flexDirection: 'column-reverse' }}
+            style={{
```
Comment (bigint) [inline src/components/Messages/MessagesList.tsx:141]: **suggestion:** can we use tailwind classes here?

Comment (bhavya2611) [reply src/components/Messages/MessagesList.tsx]: Done

**Review by bigint — APPROVED** [review]
