### PR TITLE
fix: profile preview 404

### LINKED ISSUE #1481: Don't show user preview if it not exists
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sasicodes**
## What does this PR do?

Fixes #1481

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bigint** [comment]
@sasicodes still i can see here `0xf8c5-0x4e`

image

**Comment by sasicodes** [comment]
> 0xf8c5-0x4e

Fixed

File: apps/web/src/components/utils/matchers/MentionMatcher.tsx [hunk 1]
```diff
@@ -49,6 +51,16 @@ export class MentionMatcher extends Matcher {
...
+    const urlResponse = urlMatcher.match(value);
+    if (urlResponse) {
+      const { host } = urlResponse;
+      const tld = host.slice(host.lastIndexOf('.') + 1).toLowerCase();
+      const ALLOWED_MENTIONS = ['lens', 'test'];
+      if (!ALLOWED_MENTIONS.includes(tld)) {
+        return null;
+      }
+    }
     return this.doMatch(value, /@[\w.-]+/, (matches) => {
```
Comment (bigint) [inline apps/web/src/components/utils/matchers/MentionMatcher.tsx:64]:
```suggestion
    }

    return this.doMatch(value, /@[\w.-]+/, (matches) => {
```

**Review by bigint — APPROVED** [review]
