### PR TITLE
fix: keep auth modal when no profile was found

### LINKED ISSUE #1497: "Claim your Lens profile" dialog disappears instantly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Claim your Lens profile" dialog just flashes, almost to fast to recognize at all.
It happens when trying to login with an Ethereum address that doesn't have a Lens account.
See [screen recording](https://user-images.githubusercontent.com/667227/210183402-c9506080-b82f-490f-9974-f87dca73c9de.mp4)

On testnet, the same problem happens with the "Sign up to Lenster" dialog

### Expected Behavior

The "Claim your Lens profile" dialog should show as normal, without closing instantly.

### Steps To Reproduce

- In wallet (e.g. Metamask), select an account/address that doesn't have a Lens account.
- On Lenster website, click Login, and then "Sign-In with Lens" in the dialog that pops up.
- Sign with wallet

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### PR DESCRIPTION
**Pull request by foolo**
## What does this PR do?

Avoid closing the login form when it should show "Claim your Lens profile".
[Screen recording](https://user-images.githubusercontent.com/667227/210209658-06a5fd1f-5bde-4184-9168-1b23e4542293.mp4)

Notes:
The three dialogs "Connect your wallet", "Please sign the message" and "Claim your Lens profile" use the same modal (apps/web/src/components/Shared/Login/index.tsx).
When the user tries to login with an address that has no account, the "Claim your Lens profile" should display. Therefor, in that scenario, the modal should not be closed.

Fixes #1497

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

In #1497, perform steps to reproduce and verify expected behavior

### CODE REVIEW

File: apps/web/src/components/Shared/Login/WalletSelector.tsx [hunk 1]
```diff
@@ -57,6 +57,7 @@ const WalletSelector: FC<Props> = ({ setHasConnected, setHasProfile }) => {
   };
 
   const handleSign = async () => {
+    let keepModal = false;
```
Comment (foolo) [inline apps/web/src/components/Shared/Login/WalletSelector.tsx:60]: An alternative to adding a bool flag would be to add `setShowAuthModal(false);` in three places. I tried it but I thought it looked less clean and less future proof.

**Review by bigint — APPROVED** [review]
