### PR TITLE
fix: oembed issues and quote post issue

### LINKED ISSUE #3576: Quoting publication not working on single publication page

### PR DESCRIPTION
**Pull request by bhavya2611**
## What does this PR do?

Fixes Oembed issue

## Related issues

Fixes #3576 , #3575 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Emoji

🚀

### CODE REVIEW

File: apps/web/src/components/Publication/PublicationBody.tsx [hunk 1]
```diff
@@ -36,16 +37,19 @@ const PublicationBody: FC<PublicationBodyProps> = ({
...
-  let content = metadata?.content;
   const filterId = snapshotProposalId || quotedPublicationId;
 
-  if (filterId) {
-    for (const url of urls) {
-      if (url.includes(filterId)) {
-        content = content?.replace(url, '');
+  const [content, setContent] = useState(metadata?.content);
+
+  useEffect(() => {
```
Comment (bigint) [inline apps/web/src/components/Publication/PublicationBody.tsx:44]: useEffect is not suggested here 🙈 

https://overreacted.io/a-complete-guide-to-useeffect/

**Review by bigint — APPROVED** [review]
