### PR TITLE
fix: zustand warning about deprecated fields

### LINKED ISSUE #2155: `getStorage` warning

### PR DESCRIPTION
**Pull request by foolo**
## What does this PR do?

Fixes #2155

## Type of change

- [x] Enhancement (non-breaking small changes to existing functionality)

## How should this be tested?

Verify loading/storing of unsent messages (lenster.xyz/messages).
Verify that the badge (red dot) for new messages works.

### CODE REVIEW

File: apps/web/src/store/message.ts [hunk 1]
```diff
@@ -143,25 +143,35 @@ export const useMessagePersistStore = create(
...
-        data.state.showMessagesBadge = new Map(data.state.showMessagesBadge);
-        data.state.unsentMessages = new Map(data.state.unsentMessages);
-        return data;
+          const data = JSON.parse(jsonData);
+          data.state.viewedMessagesAtNs = new Map(data.state.viewedMessagesAtNs);
+          data.state.showMessagesBadge = new Map(data.state.showMessagesBadge);
+          data.state.unsentMessages = new Map(data.state.unsentMessages);
+          return data;
+        },
+        removeItem(name) {
```
Comment (bigint) [inline apps/web/src/store/message.ts:172]: Do we need this function?

**Review by bigint — CHANGES_REQUESTED** [review]

File: apps/web/src/store/message.ts (hunk 1 above)
Comment (bigint) [reply apps/web/src/store/message.ts:172]: Gotcha

**Review by bigint — APPROVED** [review]
**LGTM** :shipit: 

Rad LGTM
