### PR TITLE
fix: dm search dropdown, quote overlay, and menu items alignment

### LINKED ISSUE #3028: Search dropdown in new message modal is transparent
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

bug

### LINKED ISSUE #3563: Invalid alignment of profile menu items in mobile
Image

### LINKED ISSUE #3564: Items in quoted posts exceeds the layout
Image

### PR DESCRIPTION
**Pull request by bhavya2611**
## What does this PR do?

Fixes UI issues

## Related issues

Fixes #3028
Fixes #3563
Fixes #3564

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Emoji

🚀

### CODE REVIEW

File: apps/web/src/components/Publication/PublicationHeader.tsx [hunk 1]
```diff
@@ -54,7 +54,11 @@ const PublicationHeader: FC<PublicationHeaderProps> = ({
       )}
       data-testid={`publication-${publication.id}-header`}
     >
-      <span onClick={stopEventPropagation} aria-hidden="true">
+      <span
+        className="max-w-[100%]"
```
Comment (bigint) [inline apps/web/src/components/Publication/PublicationHeader.tsx:58]: `max-w-full` didnt worked?

**Review by bigint — CHANGES_REQUESTED** [review]

**Review by bigint — APPROVED** [review]
**LGTM** :shipit: 

LGTM
