### PR TITLE
fix: persistent state issue across comments and posts

### LINKED ISSUE #3540: Use separate states for post and comments
https://user-images.githubusercontent.com/69431456/261036893-cc1fa29a-19e5-4ff3-bf55-c984aa574249.mov

### PR DESCRIPTION
**Pull request by bhavya2611**
## What does this PR do?

Fix the state issue being stored across comments and posts

## Related issues

Fixes #3540 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Explanation of the changes

Reset the state on unmount and also made sure comment dialog shows only when user is not in the new post modal flow

## Emoji

🚀

### CODE REVIEW

File: apps/web/src/store/modals.ts [hunk 1]
```diff
@@ -6,6 +6,8 @@ interface GlobalModalState {
   setShowAuthModal: (showAuthModal: boolean) => void;
   showNewPostModal: boolean;
   setShowNewPostModal: (showNewPostModal: boolean) => void;
+  showDiscardModal: boolean;
+  setShowDiscardModal: (showNewPostModal: boolean) => void;
```
Comment (bigint) [inline apps/web/src/store/modals.ts:10]:
```suggestion
  setShowDiscardModal: (showDiscardModal: boolean) => void;
```

**Review by bigint — APPROVED** [review]
